export const DEFAULT_GENRE = `All genres`;

export const ActionType = {
  CHANGE_ACTIVE_GENRE: `CHANGE_ACTIVE_GENRE`,
  INCREMENT_COUNT_OF_VISIBLE_MOVIES: `INCREMENT_COUNT_OF_VISIBLE_MOVIES`,
};

export const INITIAL_COUNT_VISIBLE_MOVIES_ON_MAIN_PAGE = 3;
